Basic UI
Joel-100/OOP-School-Lib pull request #4
Opened 2022-12-22 18:45 UTC by Joel-100

- Created app.rb file that will serve as your console app entry point.
- Created main.rb which defines the entry point
- Created separated files create_student, create_teacher, rent_out_book.rb and list_rentals.rb

2022-12-22 20:11 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Joel-100 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 20:11 UTC, tresorsawasawa commented on person.rb
>  end
- [ ] Kindly make sure you correct the typing error while importing your files at the top of this file(`person.rb`) as it raises an error while running your application. 
```ruby
# Bad
require './captalize'

# Good
require './capitalize'
```

2022-12-22 20:11 UTC, tresorsawasawa commented on rent_out_book.rb
> +  end
- [ ] Kindly make sure the user is able to `Create a rental` as shown in the template **[video](https://www.youtube.com/watch?v=vkkgrhD6aXQ)**. Right now, when clicking the **Option 5 for creating a rental**, after the user has entered the `date`, your app shows the below error, make sure you fix it:
![Screenshot from 2022-12-22 21-57-31](https://user-images.githubusercontent.com/83042742/209216690-36cf1b42-1c6b-41c0-a2ac-21bff9651336.png)

2022-12-22 20:11 UTC, tresorsawasawa commented on list_rentals.rb
> +    end
- [ ] As option **5** for creating a rental is not working, it is impossible to also check if the **6th option of listing all rentals for a given person is** working as expected. By this I mean, once you have fixed the issue of creating a rental, you should make sure the user is able to list **all rentals for a given person** to make your App be complete. 

Good :+1: job as other options are working as expected

2022-12-23 06:51 UTC, julie-ify approved these changes
Hi @Joel-100,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-02 13:06 UTC, merged